### ISSUE TITLE
Add "fadeout" effect

### ISSUE THREAD

**Issue by EugeneKay** [EugeneKay/it-vends#3]
The output generated by the "Vend!" button should fade out after not clicking the button for some time. 15 seconds? This should not require the addition of any additional jQuery libraries, as there is already a .fadeOut() function we can use. Implementation should be simple, boiling down to chaining a timer onto the Vend! button.

**Comment by Kyte** [comment]
Done. 'cause why not.

**Comment by EugeneKay** [comment]
This implementation does not handle re-clicks effectively, because it uses the "dumb" delay timer. We need to implement a resetable timer before this can be considered "Done".

**Comment by EugeneKay** [comment]
Added the jQuery doTimeout plugin in 0133d55, and switched from .delay() to .doTimeOut. Works great.
