### ISSUE TITLE
Button not styled when js is off

### ISSUE THREAD

**Issue by Kindari** [EugeneKay/it-vends#5]
Title says it all.

**Comment by EugeneKay** [comment]
Closing this, will not be fixing it. The button styling is applied by the jQuery UI Button Widget, and reinventing the wheel just to get better styling to the minority of NoScript users(when we are already serving them by falling back to a ?action=vend link) is not something I will be putting time+effort into. If you like, create a feature branch for this and reopen it once there's some progress.
